### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by senapk** [senapk/th#1]
- [ ] retornar a nota do usuário para escrever os testes
- [x] adicionar suporte ao update no md
- [x] colocar o update para 
    - [x] remover duplicados automaticamente
    - [x] atualizar nome e retirar suporte a atualizar pastas

**Comment by senapk** [comment]
finalizado o suporte ao update de arquivos md com testes no formato tio
correção do update e refatoração
